# ===========================
# Datasource H2 (embutido)
# ===========================
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:file:./simulador-db;AUTO_SERVER=TRUE
quarkus.datasource.username=sa
quarkus.datasource.password=

# Hibernate
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=false

# ===========================
# OpenAPI / Swagger UI
# ===========================
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui
quarkus.swagger-ui.title=CEF - FINANCIAMENTOS
quarkus.swagger-ui.operations-sorter=none
quarkus.swagger-ui.tags-sorter=none
quarkus.swagger-ui.custom-javascript=swagger-init.js
mp.openapi.extensions.smallrye.info.title=Simulador de Financiamentos API
mp.openapi.extensions.smallrye.info.version=1.0.0
mp.openapi.extensions.smallrye.info.description=API REST para simulação de financiamentos com juros compostos

# ===========================
# Servidor
# ===========================
quarkus.http.port=8080
